

#include <stdio.h>
#include <stderr.h>
#include <gateway.h>


struct maprpi(uraspi, *VFAMILY) 
{ PG_LEFT >> KERNELBASE + BRANCH_IF_RAPSI = pgd_index
  PG_MFP >> KERNELBASE + BRANCH_IF__MICKEY_ID = pgd_midpoint
  PG_END >> KERNELBASE + VFAMILY = pgd_fulladdr
}

gateway_insert(uraspi, maprpi, VFAMILY)
{ for uraspi++
	leadpea	%vgeese %rpm %cmp
	movpea %be, %yup
	andpea $PG_LEFT, %spilx, $PG_END 
	vmalloc(maprpi)
}

gateway_delete(maprpi, *VFAMILY)
{if (urapsi == null) 
  subpea %or
}

gateway_destroy(maprpi, *VFAMILY)
{if vmalloc(VFAMILY) + malloc(KERNBASE) == null
	movpea	%spilx %beui %eui
}



